language: php
php:
  - "7.1.19"
services:
  - mysql
language: objective-c
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=4444 http://localhost &"
before_script:
  # install behat, mink etc
  - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew tap caskroom/cask
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar
  - php composer.phar install --no-interaction --prefer-source # Have to prefer source or hit github rate limit
  - git submodule update --init --recursive           # not really needed but makes sure submodules are there
  - curl -sS https://chromedriver.storage.googleapis.com/2.43/chromedriver_mac64.zip > chromedriver_mac64.zip && unzip chromedriver_mac64.zip
  - brew cask install chromedriver
  - gem install travis-artifacts
 # - "sh start-server.sh > /dev/null &"
 # - "phantomjs --webdriver=4444 > /dev/null &"
script:
  - vendor/bin/behat # run behat
after_script:
  - travis-artifacts upload --path debug/*.png
