language: php
php:
  - "7.1.19"
services:
  - mysql
before_script:
  # install behat, mink etc
  - composer install --no-interaction --prefer-source # Have to prefer source or hit github rate limit
  - git submodule update --init --recursive           # not really needed but makes sure submodules are there
script:
  - vendor/bin/behat # run behat
