dist: trusty
sudo: required
language: php
addons:
  chrome: stable
before_install:
  - "/opt/google/chome/chrome-sandbox --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
before_script:
  # ensure we have access to chrome
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
  # install behat, mink etc
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar
  - php composer.phar install --no-interaction --prefer-source # Have to prefer source or hit github rate limit
  - git submodule update --init --recursive           # not really needed but makes sure submodules are there
script:
  - vendor/bin/behat # run behat
addons:
  artifacts:
    paths:
      - $(find ./debug/ -type f | tr "\n" ":")