language: php
php:
  - "7.1.19"
services:
  - mysql
language: objective-c
addons:
  artifacts: true
  paths:
    - $(ls ./debug/*.png | tr "\n" ":")
  chrome: beta
before_install:
  - # start your web application and listen on `localhost`
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
before_script:
  # install behat, mink etc
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar
  - php composer.phar install --no-interaction --prefer-source # Have to prefer source or hit github rate limit
  - git submodule update --init --recursive           # not really needed but makes sure submodules are there
script:
  - vendor/bin/behat # run behat
