dist: trusty
sudo: required
language: php
php:
  - "7.1.19"
env:
  global:
    - CHROME_BIN=/usr/bin/google-chrome
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - oracle-java8-set-default
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "wget https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip && unzip chromedriver_linux64.zip && sudo mv chromedriver /usr/bin"
  - "export DISPLAY=:99.0"
  - "curl -sS https://getcomposer.org/installer | php"
  - "php composer.phar"
  - "php composer.phar install --no-interaction --prefer-source"
  - "./bin/selenium-server-standalone > /dev/null &"
  - sleep 5
script:
  - bin/behat # run behat
